# -*- mode: ruby -*-
# vi: set ft=ruby :
$script = <<-SCRIPT
cat <<EOF > /etc/apt/apt.conf.d/01acng
Acquire::http {
        Proxy-Auto-Detect "/vagrant/detect-proxy.sh";
        };

EOF
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: $script
  config.vm.provision "shell", path: "provision-common.sh"

  config.vm.define "aptcache", autostart: false do |aptcache|
    aptcache.vm.box = "hashicorp/bionic64"
    aptcache.vm.network "private_network", ip: "192.168.33.9"
    aptcache.vm.hostname = "aptcache"
    aptcache.vm.provision "shell", path: "provision-apt_cacher_ng.sh"
    aptcache.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
    aptcache.vm.synced_folder ".", "/vagrant", mount_options: ["uid=112", "gid=115"]
  end

  config.vm.define "tshark" do |tshark|
    tshark.vm.box = "hashicorp/bionic64"
    tshark.vm.network "private_network", ip: "192.168.33.10"
    tshark.vm.hostname = "tshark"
    tshark.vm.provision "shell", path: "provision-tshark.sh"
    tshark.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      # enable promiscuous mode on the private network
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
    end
  end

  config.vm.define "db" do |db|
    db.vm.box = "hashicorp/bionic64"
    db.vm.network "private_network", ip: "192.168.33.12"
    db.vm.hostname = "db"
    db.vm.provision "shell", path: "provision-db.sh"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

  config.vm.define "web" do |web|
    web.vm.box = "hashicorp/bionic64"
    web.vm.network "private_network", ip: "192.168.33.11"
    web.vm.hostname = "web"
    web.vm.provision "shell", path: "provision-web.sh"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end    
  end

  config.vm.define "compromised" do |compromised|
    compromised.vm.box = "hashicorp/bionic64"
    compromised.vm.network "private_network", ip: "192.168.33.66"
    compromised.vm.hostname = "intruder"
    compromised.vm.provision "shell", path: "provision-compromised.sh"
    compromised.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end

  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

end
